export const cars = [
  {
    id: 1,
    name: 'Renault',
    year: 2018,
    mileage: 150000,
    fuel: 'Essence',
    transmission: 'Manuelle',
    location: 'Paris',
    registrationDate: '01/2004',
    origin: 'France',
    firstOwner: 'Oui',
    color: 'Rouge',
    doors: 5,
    seats: 5,
    fiscalPower: 5,
    dinPower: 100,
    consumption: 5,
    co2Emissions: 500,
    critAir: 2,
    price: 8500,
    image: '/images/car1.jpg',
    seller: {
      name: 'Jean Dupont',
      profileImage: '/images/seller-jean.jpg',
      rating: 4.7,
      memberSince: 'Janvier 2020',
      location: 'Paris, France'
    }
  },
  {
    id: 2,
    name: 'BMW',
    year: 2019,
    mileage: 150000,
    fuel: 'Essence',
    transmission: 'Manuelle',
    location: 'Paris',
    registrationDate: '01/2004',
    origin: 'France',
    firstOwner: 'Oui',
    color: 'Rouge',
    doors: 5,
    seats: 5,
    fiscalPower: 5,
    dinPower: 100,
    consumption: 5,
    co2Emissions: 500,
    critAir: 2,
    price: 9500,
    image: '/images/car2.jpg',
    seller: {
      name: 'Marie Leblanc',
      profileImage: '/images/seller-marie.jpg',
      rating: 4.6,
      memberSince: 'Mars 2021',
      location: 'Lyon, France'
    }
  },
  {
    id: 3,
    name: 'Renault',
    year: 2020,
    mileage: 150000,
    fuel: 'Essence',
    transmission: 'Manuelle',
    location: 'Paris',
    registrationDate: '01/2004',
    origin: 'France',
    firstOwner: 'Oui',
    color: 'Rouge',
    doors: 5,
    seats: 5,
    fiscalPower: 5,
    dinPower: 100,
    consumption: 5,
    co2Emissions: 500,
    critAir: 2,
    price: 15000,
    image: '/images/car3.png',
    seller: {
      name: 'Pierre Martin',
      profileImage: '/images/seller-pierre.jpg',
      rating: 4.8,
      memberSince: 'Avril 2019',
      location: 'Marseille, France'
    }
  },
  {
    id: 4,
    name: 'Peugeot',
    year: 2020,
    mileage: 150000,
    fuel: 'Essence',
    transmission: 'Manuelle',
    location: 'Paris',
    registrationDate: '01/2004',
    origin: 'France',
    firstOwner: 'Oui',
    color: 'Rouge',
    doors: 5,
    seats: 5,
    fiscalPower: 5,
    dinPower: 100,
    consumption: 5,
    co2Emissions: 500,
    critAir: 2,
    price: 15000,
    image: '/images/car4.jpg',
    seller: {
      name: 'Sophie Durand',
      profileImage: '/images/seller-sophie.jpg',
      rating: 4.9,
      memberSince: 'Février 2021',
      location: 'Nice, France'
    }
  },
  {
    id: 5,
    name: 'Mercedes',
    year: 2020,
    mileage: 150000,
    fuel: 'Essence',
    transmission: 'Manuelle',
    location: 'Paris',
    registrationDate: '01/2004',
    origin: 'France',
    firstOwner: 'Oui',
    color: 'Rouge',
    doors: 5,
    seats: 5,
    fiscalPower: 5,
    dinPower: 100,
    consumption: 5,
    co2Emissions: 500,
    critAir: 2,
    price: 15000,
    image: '/images/car5.jpg',
    seller: {
      name: 'Lucas Bernard',
      profileImage: '/images/seller-lucas.jpg',
      rating: 4.5,
      memberSince: 'Mai 2018',
      location: 'Bordeaux, France'
    }
  },
  {
    id: 6,
    name: 'Volkswagen',
    year: 2020,
    mileage: 150000,
    fuel: 'Essence',
    transmission: 'Manuelle',
    location: 'Paris',
    registrationDate: '01/2004',
    origin: 'France',
    firstOwner: 'Oui',
    color: 'Rouge',
    doors: 5,
    seats: 5,
    fiscalPower: 5,
    dinPower: 100,
    consumption: 5,
    co2Emissions: 500,
    critAir: 2,
    price: 15000,
    image: '/images/car6.jpg',
    seller: {
      name: 'Emma Roussel',
      profileImage: '/images/seller-emma.jpg',
      rating: 4.7,
      memberSince: 'Juin 2020',
      location: 'Toulouse, France'
    }
  },
  {
    id: 7,
    name: 'Peugeot',
    year: 2020,
    mileage: 150000,
    fuel: 'Essence',
    transmission: 'Manuelle',
    location: 'Paris',
    registrationDate: '01/2004',
    origin: 'France',
    firstOwner: 'Oui',
    color: 'Rouge',
    doors: 5,
    seats: 5,
    fiscalPower: 5,
    dinPower: 100,
    consumption: 5,
    co2Emissions: 500,
    critAir: 2,
    price: 15000,
    image: '/images/car7.jpg',
    seller: {
      name: 'Emma Roussel',
      profileImage: '/images/seller-emma.jpg',
      rating: 4.7,
      memberSince: 'Juin 2020',
      location: 'Toulouse, France'
    }
  },
  {
    id: 8,
    name: 'Opel',
    year: 2020,
    mileage: 150000,
    fuel: 'Essence',
    transmission: 'Manuelle',
    location: 'Paris',
    registrationDate: '01/2004',
    origin: 'France',
    firstOwner: 'Oui',
    color: 'Rouge',
    doors: 5,
    seats: 5,
    fiscalPower: 5,
    dinPower: 100,
    consumption: 5,
    co2Emissions: 500,
    critAir: 2,
    price: 15000,
    image: '/images/car8.jpg',
    seller: {
      name: 'Emma Roussel',
      profileImage: '/images/seller-emma.jpg',
      rating: 4.7,
      memberSince: 'Juin 2020',
      location: 'Toulouse, France'
    }
  }
];
